Crud productv1
Mosi-Rivera/RetoCompraServer pull request #33
Opened 2024-04-06 13:43 UTC by JaniQuiRo

Adding routes and controller for Crud Products and variants

2024-04-06 14:26 UTC, Mosi-Rivera requested changes
Tu puedes!

2024-04-06 14:26 UTC, Mosi-Rivera commented on controllers/product_controllers.js
> +        const user = await Product.findOneAndUdpate(_id, name, description, section, brand);
findOneAndUpdate tiene 3 objetos como argumento. El tercero es opcional.
https://mongoosejs.com/docs/api/model.html#Model.findOneAndUpdate()
1.select/match: Como vas seleccionar el document que quiered devolver. En este caso por _id.
2. update: Que quieres cambiar. {name, description, section, brand}
3. config: En este caso puedes user {new: true} si quieres que devuelva el documento luego de ser modificado, o si no dejarlo vacio.

2024-04-06 14:26 UTC, Mosi-Rivera commented on controllers/product_controllers.js
> +        const user = await Product.prodRemove(_id, name, description, section, brand);
En este usarias Product.findByIdAndDelete():
https://mongoosejs.com/docs/api/model.html#Model.findByIdAndDelete()
Tambien tendiras que asegurarte de borrar todos las variantes que hagan referencia a ese producto (Como cascade en sql).
Habria que implement algo asi en 'models/product.js'
// Define the 'pre' hook for 'remove' method of Product model
productSchema.pre('remove', async function(next) {
  try {
    // Delete all variants associated with this product
    await Variant.deleteMany({ product: this._id });
    next();
  } catch (error) {
    next(error);
  }
});

Enfocate en las demas y deja esta para lo ultimo cuando ya tengas mas experiencia. Despues la miramos juntos si te parece dificil.

2024-04-06 14:26 UTC, Mosi-Rivera commented on controllers/product_controllers.js
> +        const user = await Product.prodAdd( name, description, section, brand);
En esta usarias Product.create() pasandole un objecto que vendria siendo el documento que quieres crear:
{name, description, section, brand}
https://mongoosejs.com/docs/api/model.html#Model.create()

2024-04-06 14:26 UTC, Mosi-Rivera commented on controllers/product_controllers.js
> +        const user = await Variant.varUpdate(_id,stock,color, price, assets);
Lo mismo que en la update de product.

2024-04-06 14:26 UTC, Mosi-Rivera commented on controllers/product_controllers.js
> +        const user = await Variant.varRemove(_id,stock,color, price, assets);
Aqui same que en la de product pero no hace falta hacer el cascade. Puedes borrar el variant y ya.

2024-04-06 14:26 UTC, Mosi-Rivera commented on controllers/product_controllers.js
> +        const user = await Variant.varAdd( stock,color, price, assets);
Ok aqui es que tiene que ponerse la logica de cloudinary para subir la foto y recibir el url. Ademas tienes que poder recibir el file de la foto desde el frontend. Esta dejala para que la hagas con daniel para que el pueda practicarlo tambien.

2024-04-06 14:26 UTC, Mosi-Rivera commented on routes/product_routes.js
> +router.route('/api/crudProductsroutes').patch(updateCrudProduct);
lo mismo en las demas crud routes.

2024-04-06 14:26 UTC, Mosi-Rivera commented on routes/product_routes.js
> +router.route('/api/crudProductsroutes').patch(updateCrudProduct);
Ademas hace falta usae el middleware de authenticateToken y validar el role de el usuario. Voy a escribir el middleware de role para que lo tengas listo cuando lo trabajes. Lo voy a poner en "middelware/roleGuard.js".

2024-04-09 13:25 UTC, Mosi-Rivera requested changes
Son los mismos cambios que te dije ayer para que los tengas de referencia aqui.

2024-04-09 13:25 UTC, Mosi-Rivera commented on controllers/product_controllers.js
> +        const  _id = req._id;
Leer _id de req.body.

2024-04-09 13:25 UTC, Mosi-Rivera commented on controllers/product_controllers.js
> +        const user = await Product.findByIdAndUpdate({_id},{name, description, section, brand}, {});
Cambiar variable de "user" a algo que describa la data que tiene.

2024-04-09 13:25 UTC, Mosi-Rivera commented on controllers/product_controllers.js
> +        const user = await Product.findByIdAndUpdate({_id},{name, description, section, brand}, {});
Pasarle new con valor de true a config para tener la version mas nueva de el documento y devolverselo al client.

2024-04-09 13:25 UTC, Mosi-Rivera commented on routes/product_routes.js
> +router.route('/crudProductsroutes').patch(updateCrudProduct);
Usar middleware de authenticateToken y validateRole en todas las rutas de crud.
validateRole no esta creado todavia, lo voy a crear ahora; va a estar bajo"middleware/validate_role.js"

2024-04-09 13:25 UTC, Mosi-Rivera commented on models/Product.js
> +ProductSchema.pre('remove')  = async(next) =>
pasarle el metodo como callback despues de 'remove'.

2024-04-12 00:08 UTC, JaniQuiRo commented on controllers/product_controllers.js
> +        const user = await Product.findOneAndUdpate(_id, name, description, section, brand);
Changed done

2024-04-12 00:08 UTC, JaniQuiRo commented on controllers/product_controllers.js
> +        const user = await Variant.varAdd( stock,color, price, assets);
Changed done

2024-04-12 00:08 UTC, JaniQuiRo commented on controllers/product_controllers.js
> +        const  _id = req._id;
Changed done

2024-04-12 00:08 UTC, JaniQuiRo commented on models/Product.js
> +ProductSchema.pre('remove')  = async(next) =>
Changed done

2024-04-12 00:08 UTC, JaniQuiRo commented on routes/product_routes.js
> +router.route('/crudProductsroutes').patch(updateCrudProduct);
Changed done

2024-04-12 00:09 UTC, Mosi-Rivera approved these changes
Fantastic plus amazing omaygawd

2024-04-12 00:10 UTC, merged